### ISSUE TITLE
Tabel definition users in users.sqlite.db correct?

### ISSUE THREAD

**Issue by EdwinHuijsing** [nette-examples/user-authentication#10]
On the moment i am testing this setup (in Docker) with sqlite as db.
It took me long to understand that i had a problem with path setting,
after setting my path to 777 all worked.

Due to all the testing in enter the same user again and got know error.
When checking the sqlite db i saw the same user two times in the db.
On looking to the definitions of the users table i noted that it is not the
same as in the users.sqlite.sql.

In the sql file there is this definition ```UNIQUE KEY `username` (`username`)``` 

But in the sqlite file the UNIQUE flag is not present.

Update:
I just did a quick test, added the flag in a empty db and copied it into the directory i use.
Then created a user, now when i try to add the same user again i get the expected error

**Comment by dg** [comment]
Thanks for the note, I fixed the database
