### ISSUE TITLE
Cannot use the included sqlite database with create-user.php script.

### ISSUE THREAD

**Issue by marekrost** [nette-examples/user-authentication#5]
The table users included within the file `users.sqlite.db` contains NOT NULL constraint on the role column.

Attempting to use `bin/create-user.php` with this database will result in the following error:

```
ERROR: SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: users.role
Check log to see more info.
```

**Comment by dg** [comment]
fixed
